version: '2'
services:
 
  bme280:
    build:
      context: .
    restart: always
    container_name: bme280
    devices:
      - "/dev/i2c-0:/dev/i2c-0"
      - "/dev/i2c-1:/dev/i2c-1"
    depends_on:
      - influxdb
      - grafana

  grafana: 
    image: fg2it/grafana-armhf:v4.1.2
    restart: always
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

  influxdb: 
    image: influxdb
    restart: always
    container_name: influxdb
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: casa_meteo
      INFLUXDB_USERNAME: raspie
      INFLUXDB_PASSWORD: raspie
    volumes:
      - influxdb-storage:/var/lib/influxdb

volumes:
  grafana-storage:
  influxdb-storage:
